/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardRespondenRespondenImport } from './routes/dashboard/responden/_responden'
import { Route as DashboardPengaduPengaduImport } from './routes/dashboard/pengadu/_pengadu'
import { Route as DashboardPegawaiPegawaiImport } from './routes/dashboard/pegawai/_pegawai'
import { Route as DashboardAdminAdminImport } from './routes/dashboard/admin/_admin'
import { Route as DashboardRespondenRespondenIndexImport } from './routes/dashboard/responden/_responden.index'
import { Route as DashboardPengaduPengaduIndexImport } from './routes/dashboard/pengadu/_pengadu.index'
import { Route as DashboardPegawaiPegawaiIndexImport } from './routes/dashboard/pegawai/_pegawai.index'
import { Route as DashboardAdminAdminIndexImport } from './routes/dashboard/admin/_admin.index'
import { Route as DashboardRespondenRespondenSenaraiAduanImport } from './routes/dashboard/responden/_responden/senarai-aduan'
import { Route as DashboardPengaduPengaduSenaraiAduanImport } from './routes/dashboard/pengadu/_pengadu/senarai-aduan'
import { Route as DashboardPegawaiPegawaiSenaraiAduanImport } from './routes/dashboard/pegawai/_pegawai/senarai-aduan'
import { Route as DashboardRespondenRespondenAduanBaruBorang2Import } from './routes/dashboard/responden/_responden/aduan-baru/borang-2'
import { Route as DashboardPengaduPengaduAduanBaruBorang1Import } from './routes/dashboard/pengadu/_pengadu/aduan-baru/borang-1'
import { Route as DashboardPegawaiPegawaiAduanBaruBorang4Import } from './routes/dashboard/pegawai/_pegawai/aduan-baru/borang-4'
import { Route as DashboardPegawaiPegawaiAduanBaruBorang3Import } from './routes/dashboard/pegawai/_pegawai/aduan-baru/borang-3'
import { Route as DashboardAdminAdminManageInternalUsersImport } from './routes/dashboard/admin/_admin/manage/internal-users'
import { Route as DashboardAdminAdminManageExternalUsersImport } from './routes/dashboard/admin/_admin/manage/external-users'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const DashboardRespondenImport = createFileRoute('/dashboard/responden')()
const DashboardPengaduImport = createFileRoute('/dashboard/pengadu')()
const DashboardPegawaiImport = createFileRoute('/dashboard/pegawai')()
const DashboardAdminImport = createFileRoute('/dashboard/admin')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardRespondenRoute = DashboardRespondenImport.update({
  id: '/dashboard/responden',
  path: '/dashboard/responden',
  getParentRoute: () => rootRoute,
} as any)

const DashboardPengaduRoute = DashboardPengaduImport.update({
  id: '/dashboard/pengadu',
  path: '/dashboard/pengadu',
  getParentRoute: () => rootRoute,
} as any)

const DashboardPegawaiRoute = DashboardPegawaiImport.update({
  id: '/dashboard/pegawai',
  path: '/dashboard/pegawai',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAdminRoute = DashboardAdminImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRespondenRespondenRoute =
  DashboardRespondenRespondenImport.update({
    id: '/_responden',
    getParentRoute: () => DashboardRespondenRoute,
  } as any)

const DashboardPengaduPengaduRoute = DashboardPengaduPengaduImport.update({
  id: '/_pengadu',
  getParentRoute: () => DashboardPengaduRoute,
} as any)

const DashboardPegawaiPegawaiRoute = DashboardPegawaiPegawaiImport.update({
  id: '/_pegawai',
  getParentRoute: () => DashboardPegawaiRoute,
} as any)

const DashboardAdminAdminRoute = DashboardAdminAdminImport.update({
  id: '/_admin',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardRespondenRespondenIndexRoute =
  DashboardRespondenRespondenIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRespondenRespondenRoute,
  } as any)

const DashboardPengaduPengaduIndexRoute =
  DashboardPengaduPengaduIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPengaduPengaduRoute,
  } as any)

const DashboardPegawaiPegawaiIndexRoute =
  DashboardPegawaiPegawaiIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPegawaiPegawaiRoute,
  } as any)

const DashboardAdminAdminIndexRoute = DashboardAdminAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminAdminRoute,
} as any)

const DashboardRespondenRespondenSenaraiAduanRoute =
  DashboardRespondenRespondenSenaraiAduanImport.update({
    id: '/senarai-aduan',
    path: '/senarai-aduan',
    getParentRoute: () => DashboardRespondenRespondenRoute,
  } as any)

const DashboardPengaduPengaduSenaraiAduanRoute =
  DashboardPengaduPengaduSenaraiAduanImport.update({
    id: '/senarai-aduan',
    path: '/senarai-aduan',
    getParentRoute: () => DashboardPengaduPengaduRoute,
  } as any)

const DashboardPegawaiPegawaiSenaraiAduanRoute =
  DashboardPegawaiPegawaiSenaraiAduanImport.update({
    id: '/senarai-aduan',
    path: '/senarai-aduan',
    getParentRoute: () => DashboardPegawaiPegawaiRoute,
  } as any)

const DashboardRespondenRespondenAduanBaruBorang2Route =
  DashboardRespondenRespondenAduanBaruBorang2Import.update({
    id: '/aduan-baru/borang-2',
    path: '/aduan-baru/borang-2',
    getParentRoute: () => DashboardRespondenRespondenRoute,
  } as any)

const DashboardPengaduPengaduAduanBaruBorang1Route =
  DashboardPengaduPengaduAduanBaruBorang1Import.update({
    id: '/aduan-baru/borang-1',
    path: '/aduan-baru/borang-1',
    getParentRoute: () => DashboardPengaduPengaduRoute,
  } as any)

const DashboardPegawaiPegawaiAduanBaruBorang4Route =
  DashboardPegawaiPegawaiAduanBaruBorang4Import.update({
    id: '/aduan-baru/borang-4',
    path: '/aduan-baru/borang-4',
    getParentRoute: () => DashboardPegawaiPegawaiRoute,
  } as any)

const DashboardPegawaiPegawaiAduanBaruBorang3Route =
  DashboardPegawaiPegawaiAduanBaruBorang3Import.update({
    id: '/aduan-baru/borang-3',
    path: '/aduan-baru/borang-3',
    getParentRoute: () => DashboardPegawaiPegawaiRoute,
  } as any)

const DashboardAdminAdminManageInternalUsersRoute =
  DashboardAdminAdminManageInternalUsersImport.update({
    id: '/manage/internal-users',
    path: '/manage/internal-users',
    getParentRoute: () => DashboardAdminAdminRoute,
  } as any)

const DashboardAdminAdminManageExternalUsersRoute =
  DashboardAdminAdminManageExternalUsersImport.update({
    id: '/manage/external-users',
    path: '/manage/external-users',
    getParentRoute: () => DashboardAdminAdminRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/admin/_admin': {
      id: '/dashboard/admin/_admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminAdminImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/pegawai': {
      id: '/dashboard/pegawai'
      path: '/dashboard/pegawai'
      fullPath: '/dashboard/pegawai'
      preLoaderRoute: typeof DashboardPegawaiImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/pegawai/_pegawai': {
      id: '/dashboard/pegawai/_pegawai'
      path: '/dashboard/pegawai'
      fullPath: '/dashboard/pegawai'
      preLoaderRoute: typeof DashboardPegawaiPegawaiImport
      parentRoute: typeof DashboardPegawaiRoute
    }
    '/dashboard/pengadu': {
      id: '/dashboard/pengadu'
      path: '/dashboard/pengadu'
      fullPath: '/dashboard/pengadu'
      preLoaderRoute: typeof DashboardPengaduImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/pengadu/_pengadu': {
      id: '/dashboard/pengadu/_pengadu'
      path: '/dashboard/pengadu'
      fullPath: '/dashboard/pengadu'
      preLoaderRoute: typeof DashboardPengaduPengaduImport
      parentRoute: typeof DashboardPengaduRoute
    }
    '/dashboard/responden': {
      id: '/dashboard/responden'
      path: '/dashboard/responden'
      fullPath: '/dashboard/responden'
      preLoaderRoute: typeof DashboardRespondenImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/responden/_responden': {
      id: '/dashboard/responden/_responden'
      path: '/dashboard/responden'
      fullPath: '/dashboard/responden'
      preLoaderRoute: typeof DashboardRespondenRespondenImport
      parentRoute: typeof DashboardRespondenRoute
    }
    '/dashboard/pegawai/_pegawai/senarai-aduan': {
      id: '/dashboard/pegawai/_pegawai/senarai-aduan'
      path: '/senarai-aduan'
      fullPath: '/dashboard/pegawai/senarai-aduan'
      preLoaderRoute: typeof DashboardPegawaiPegawaiSenaraiAduanImport
      parentRoute: typeof DashboardPegawaiPegawaiImport
    }
    '/dashboard/pengadu/_pengadu/senarai-aduan': {
      id: '/dashboard/pengadu/_pengadu/senarai-aduan'
      path: '/senarai-aduan'
      fullPath: '/dashboard/pengadu/senarai-aduan'
      preLoaderRoute: typeof DashboardPengaduPengaduSenaraiAduanImport
      parentRoute: typeof DashboardPengaduPengaduImport
    }
    '/dashboard/responden/_responden/senarai-aduan': {
      id: '/dashboard/responden/_responden/senarai-aduan'
      path: '/senarai-aduan'
      fullPath: '/dashboard/responden/senarai-aduan'
      preLoaderRoute: typeof DashboardRespondenRespondenSenaraiAduanImport
      parentRoute: typeof DashboardRespondenRespondenImport
    }
    '/dashboard/admin/_admin/': {
      id: '/dashboard/admin/_admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminAdminIndexImport
      parentRoute: typeof DashboardAdminAdminImport
    }
    '/dashboard/pegawai/_pegawai/': {
      id: '/dashboard/pegawai/_pegawai/'
      path: '/'
      fullPath: '/dashboard/pegawai/'
      preLoaderRoute: typeof DashboardPegawaiPegawaiIndexImport
      parentRoute: typeof DashboardPegawaiPegawaiImport
    }
    '/dashboard/pengadu/_pengadu/': {
      id: '/dashboard/pengadu/_pengadu/'
      path: '/'
      fullPath: '/dashboard/pengadu/'
      preLoaderRoute: typeof DashboardPengaduPengaduIndexImport
      parentRoute: typeof DashboardPengaduPengaduImport
    }
    '/dashboard/responden/_responden/': {
      id: '/dashboard/responden/_responden/'
      path: '/'
      fullPath: '/dashboard/responden/'
      preLoaderRoute: typeof DashboardRespondenRespondenIndexImport
      parentRoute: typeof DashboardRespondenRespondenImport
    }
    '/dashboard/admin/_admin/manage/external-users': {
      id: '/dashboard/admin/_admin/manage/external-users'
      path: '/manage/external-users'
      fullPath: '/dashboard/admin/manage/external-users'
      preLoaderRoute: typeof DashboardAdminAdminManageExternalUsersImport
      parentRoute: typeof DashboardAdminAdminImport
    }
    '/dashboard/admin/_admin/manage/internal-users': {
      id: '/dashboard/admin/_admin/manage/internal-users'
      path: '/manage/internal-users'
      fullPath: '/dashboard/admin/manage/internal-users'
      preLoaderRoute: typeof DashboardAdminAdminManageInternalUsersImport
      parentRoute: typeof DashboardAdminAdminImport
    }
    '/dashboard/pegawai/_pegawai/aduan-baru/borang-3': {
      id: '/dashboard/pegawai/_pegawai/aduan-baru/borang-3'
      path: '/aduan-baru/borang-3'
      fullPath: '/dashboard/pegawai/aduan-baru/borang-3'
      preLoaderRoute: typeof DashboardPegawaiPegawaiAduanBaruBorang3Import
      parentRoute: typeof DashboardPegawaiPegawaiImport
    }
    '/dashboard/pegawai/_pegawai/aduan-baru/borang-4': {
      id: '/dashboard/pegawai/_pegawai/aduan-baru/borang-4'
      path: '/aduan-baru/borang-4'
      fullPath: '/dashboard/pegawai/aduan-baru/borang-4'
      preLoaderRoute: typeof DashboardPegawaiPegawaiAduanBaruBorang4Import
      parentRoute: typeof DashboardPegawaiPegawaiImport
    }
    '/dashboard/pengadu/_pengadu/aduan-baru/borang-1': {
      id: '/dashboard/pengadu/_pengadu/aduan-baru/borang-1'
      path: '/aduan-baru/borang-1'
      fullPath: '/dashboard/pengadu/aduan-baru/borang-1'
      preLoaderRoute: typeof DashboardPengaduPengaduAduanBaruBorang1Import
      parentRoute: typeof DashboardPengaduPengaduImport
    }
    '/dashboard/responden/_responden/aduan-baru/borang-2': {
      id: '/dashboard/responden/_responden/aduan-baru/borang-2'
      path: '/aduan-baru/borang-2'
      fullPath: '/dashboard/responden/aduan-baru/borang-2'
      preLoaderRoute: typeof DashboardRespondenRespondenAduanBaruBorang2Import
      parentRoute: typeof DashboardRespondenRespondenImport
    }
  }
}

// Create and export the route tree

interface DashboardAdminAdminRouteChildren {
  DashboardAdminAdminIndexRoute: typeof DashboardAdminAdminIndexRoute
  DashboardAdminAdminManageExternalUsersRoute: typeof DashboardAdminAdminManageExternalUsersRoute
  DashboardAdminAdminManageInternalUsersRoute: typeof DashboardAdminAdminManageInternalUsersRoute
}

const DashboardAdminAdminRouteChildren: DashboardAdminAdminRouteChildren = {
  DashboardAdminAdminIndexRoute: DashboardAdminAdminIndexRoute,
  DashboardAdminAdminManageExternalUsersRoute:
    DashboardAdminAdminManageExternalUsersRoute,
  DashboardAdminAdminManageInternalUsersRoute:
    DashboardAdminAdminManageInternalUsersRoute,
}

const DashboardAdminAdminRouteWithChildren =
  DashboardAdminAdminRoute._addFileChildren(DashboardAdminAdminRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminAdminRoute: typeof DashboardAdminAdminRouteWithChildren
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAdminRoute: DashboardAdminAdminRouteWithChildren,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardPegawaiPegawaiRouteChildren {
  DashboardPegawaiPegawaiSenaraiAduanRoute: typeof DashboardPegawaiPegawaiSenaraiAduanRoute
  DashboardPegawaiPegawaiIndexRoute: typeof DashboardPegawaiPegawaiIndexRoute
  DashboardPegawaiPegawaiAduanBaruBorang3Route: typeof DashboardPegawaiPegawaiAduanBaruBorang3Route
  DashboardPegawaiPegawaiAduanBaruBorang4Route: typeof DashboardPegawaiPegawaiAduanBaruBorang4Route
}

const DashboardPegawaiPegawaiRouteChildren: DashboardPegawaiPegawaiRouteChildren =
  {
    DashboardPegawaiPegawaiSenaraiAduanRoute:
      DashboardPegawaiPegawaiSenaraiAduanRoute,
    DashboardPegawaiPegawaiIndexRoute: DashboardPegawaiPegawaiIndexRoute,
    DashboardPegawaiPegawaiAduanBaruBorang3Route:
      DashboardPegawaiPegawaiAduanBaruBorang3Route,
    DashboardPegawaiPegawaiAduanBaruBorang4Route:
      DashboardPegawaiPegawaiAduanBaruBorang4Route,
  }

const DashboardPegawaiPegawaiRouteWithChildren =
  DashboardPegawaiPegawaiRoute._addFileChildren(
    DashboardPegawaiPegawaiRouteChildren,
  )

interface DashboardPegawaiRouteChildren {
  DashboardPegawaiPegawaiRoute: typeof DashboardPegawaiPegawaiRouteWithChildren
}

const DashboardPegawaiRouteChildren: DashboardPegawaiRouteChildren = {
  DashboardPegawaiPegawaiRoute: DashboardPegawaiPegawaiRouteWithChildren,
}

const DashboardPegawaiRouteWithChildren =
  DashboardPegawaiRoute._addFileChildren(DashboardPegawaiRouteChildren)

interface DashboardPengaduPengaduRouteChildren {
  DashboardPengaduPengaduSenaraiAduanRoute: typeof DashboardPengaduPengaduSenaraiAduanRoute
  DashboardPengaduPengaduIndexRoute: typeof DashboardPengaduPengaduIndexRoute
  DashboardPengaduPengaduAduanBaruBorang1Route: typeof DashboardPengaduPengaduAduanBaruBorang1Route
}

const DashboardPengaduPengaduRouteChildren: DashboardPengaduPengaduRouteChildren =
  {
    DashboardPengaduPengaduSenaraiAduanRoute:
      DashboardPengaduPengaduSenaraiAduanRoute,
    DashboardPengaduPengaduIndexRoute: DashboardPengaduPengaduIndexRoute,
    DashboardPengaduPengaduAduanBaruBorang1Route:
      DashboardPengaduPengaduAduanBaruBorang1Route,
  }

const DashboardPengaduPengaduRouteWithChildren =
  DashboardPengaduPengaduRoute._addFileChildren(
    DashboardPengaduPengaduRouteChildren,
  )

interface DashboardPengaduRouteChildren {
  DashboardPengaduPengaduRoute: typeof DashboardPengaduPengaduRouteWithChildren
}

const DashboardPengaduRouteChildren: DashboardPengaduRouteChildren = {
  DashboardPengaduPengaduRoute: DashboardPengaduPengaduRouteWithChildren,
}

const DashboardPengaduRouteWithChildren =
  DashboardPengaduRoute._addFileChildren(DashboardPengaduRouteChildren)

interface DashboardRespondenRespondenRouteChildren {
  DashboardRespondenRespondenSenaraiAduanRoute: typeof DashboardRespondenRespondenSenaraiAduanRoute
  DashboardRespondenRespondenIndexRoute: typeof DashboardRespondenRespondenIndexRoute
  DashboardRespondenRespondenAduanBaruBorang2Route: typeof DashboardRespondenRespondenAduanBaruBorang2Route
}

const DashboardRespondenRespondenRouteChildren: DashboardRespondenRespondenRouteChildren =
  {
    DashboardRespondenRespondenSenaraiAduanRoute:
      DashboardRespondenRespondenSenaraiAduanRoute,
    DashboardRespondenRespondenIndexRoute:
      DashboardRespondenRespondenIndexRoute,
    DashboardRespondenRespondenAduanBaruBorang2Route:
      DashboardRespondenRespondenAduanBaruBorang2Route,
  }

const DashboardRespondenRespondenRouteWithChildren =
  DashboardRespondenRespondenRoute._addFileChildren(
    DashboardRespondenRespondenRouteChildren,
  )

interface DashboardRespondenRouteChildren {
  DashboardRespondenRespondenRoute: typeof DashboardRespondenRespondenRouteWithChildren
}

const DashboardRespondenRouteChildren: DashboardRespondenRouteChildren = {
  DashboardRespondenRespondenRoute:
    DashboardRespondenRespondenRouteWithChildren,
}

const DashboardRespondenRouteWithChildren =
  DashboardRespondenRoute._addFileChildren(DashboardRespondenRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminAdminRouteWithChildren
  '/dashboard/pegawai': typeof DashboardPegawaiPegawaiRouteWithChildren
  '/dashboard/pengadu': typeof DashboardPengaduPengaduRouteWithChildren
  '/dashboard/responden': typeof DashboardRespondenRespondenRouteWithChildren
  '/dashboard/pegawai/senarai-aduan': typeof DashboardPegawaiPegawaiSenaraiAduanRoute
  '/dashboard/pengadu/senarai-aduan': typeof DashboardPengaduPengaduSenaraiAduanRoute
  '/dashboard/responden/senarai-aduan': typeof DashboardRespondenRespondenSenaraiAduanRoute
  '/dashboard/admin/': typeof DashboardAdminAdminIndexRoute
  '/dashboard/pegawai/': typeof DashboardPegawaiPegawaiIndexRoute
  '/dashboard/pengadu/': typeof DashboardPengaduPengaduIndexRoute
  '/dashboard/responden/': typeof DashboardRespondenRespondenIndexRoute
  '/dashboard/admin/manage/external-users': typeof DashboardAdminAdminManageExternalUsersRoute
  '/dashboard/admin/manage/internal-users': typeof DashboardAdminAdminManageInternalUsersRoute
  '/dashboard/pegawai/aduan-baru/borang-3': typeof DashboardPegawaiPegawaiAduanBaruBorang3Route
  '/dashboard/pegawai/aduan-baru/borang-4': typeof DashboardPegawaiPegawaiAduanBaruBorang4Route
  '/dashboard/pengadu/aduan-baru/borang-1': typeof DashboardPengaduPengaduAduanBaruBorang1Route
  '/dashboard/responden/aduan-baru/borang-2': typeof DashboardRespondenRespondenAduanBaruBorang2Route
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminAdminIndexRoute
  '/dashboard/pegawai': typeof DashboardPegawaiPegawaiIndexRoute
  '/dashboard/pengadu': typeof DashboardPengaduPengaduIndexRoute
  '/dashboard/responden': typeof DashboardRespondenRespondenIndexRoute
  '/dashboard/pegawai/senarai-aduan': typeof DashboardPegawaiPegawaiSenaraiAduanRoute
  '/dashboard/pengadu/senarai-aduan': typeof DashboardPengaduPengaduSenaraiAduanRoute
  '/dashboard/responden/senarai-aduan': typeof DashboardRespondenRespondenSenaraiAduanRoute
  '/dashboard/admin/manage/external-users': typeof DashboardAdminAdminManageExternalUsersRoute
  '/dashboard/admin/manage/internal-users': typeof DashboardAdminAdminManageInternalUsersRoute
  '/dashboard/pegawai/aduan-baru/borang-3': typeof DashboardPegawaiPegawaiAduanBaruBorang3Route
  '/dashboard/pegawai/aduan-baru/borang-4': typeof DashboardPegawaiPegawaiAduanBaruBorang4Route
  '/dashboard/pengadu/aduan-baru/borang-1': typeof DashboardPengaduPengaduAduanBaruBorang1Route
  '/dashboard/responden/aduan-baru/borang-2': typeof DashboardRespondenRespondenAduanBaruBorang2Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/admin/_admin': typeof DashboardAdminAdminRouteWithChildren
  '/dashboard/pegawai': typeof DashboardPegawaiRouteWithChildren
  '/dashboard/pegawai/_pegawai': typeof DashboardPegawaiPegawaiRouteWithChildren
  '/dashboard/pengadu': typeof DashboardPengaduRouteWithChildren
  '/dashboard/pengadu/_pengadu': typeof DashboardPengaduPengaduRouteWithChildren
  '/dashboard/responden': typeof DashboardRespondenRouteWithChildren
  '/dashboard/responden/_responden': typeof DashboardRespondenRespondenRouteWithChildren
  '/dashboard/pegawai/_pegawai/senarai-aduan': typeof DashboardPegawaiPegawaiSenaraiAduanRoute
  '/dashboard/pengadu/_pengadu/senarai-aduan': typeof DashboardPengaduPengaduSenaraiAduanRoute
  '/dashboard/responden/_responden/senarai-aduan': typeof DashboardRespondenRespondenSenaraiAduanRoute
  '/dashboard/admin/_admin/': typeof DashboardAdminAdminIndexRoute
  '/dashboard/pegawai/_pegawai/': typeof DashboardPegawaiPegawaiIndexRoute
  '/dashboard/pengadu/_pengadu/': typeof DashboardPengaduPengaduIndexRoute
  '/dashboard/responden/_responden/': typeof DashboardRespondenRespondenIndexRoute
  '/dashboard/admin/_admin/manage/external-users': typeof DashboardAdminAdminManageExternalUsersRoute
  '/dashboard/admin/_admin/manage/internal-users': typeof DashboardAdminAdminManageInternalUsersRoute
  '/dashboard/pegawai/_pegawai/aduan-baru/borang-3': typeof DashboardPegawaiPegawaiAduanBaruBorang3Route
  '/dashboard/pegawai/_pegawai/aduan-baru/borang-4': typeof DashboardPegawaiPegawaiAduanBaruBorang4Route
  '/dashboard/pengadu/_pengadu/aduan-baru/borang-1': typeof DashboardPengaduPengaduAduanBaruBorang1Route
  '/dashboard/responden/_responden/aduan-baru/borang-2': typeof DashboardRespondenRespondenAduanBaruBorang2Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/pegawai'
    | '/dashboard/pengadu'
    | '/dashboard/responden'
    | '/dashboard/pegawai/senarai-aduan'
    | '/dashboard/pengadu/senarai-aduan'
    | '/dashboard/responden/senarai-aduan'
    | '/dashboard/admin/'
    | '/dashboard/pegawai/'
    | '/dashboard/pengadu/'
    | '/dashboard/responden/'
    | '/dashboard/admin/manage/external-users'
    | '/dashboard/admin/manage/internal-users'
    | '/dashboard/pegawai/aduan-baru/borang-3'
    | '/dashboard/pegawai/aduan-baru/borang-4'
    | '/dashboard/pengadu/aduan-baru/borang-1'
    | '/dashboard/responden/aduan-baru/borang-2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/pegawai'
    | '/dashboard/pengadu'
    | '/dashboard/responden'
    | '/dashboard/pegawai/senarai-aduan'
    | '/dashboard/pengadu/senarai-aduan'
    | '/dashboard/responden/senarai-aduan'
    | '/dashboard/admin/manage/external-users'
    | '/dashboard/admin/manage/internal-users'
    | '/dashboard/pegawai/aduan-baru/borang-3'
    | '/dashboard/pegawai/aduan-baru/borang-4'
    | '/dashboard/pengadu/aduan-baru/borang-1'
    | '/dashboard/responden/aduan-baru/borang-2'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/admin/_admin'
    | '/dashboard/pegawai'
    | '/dashboard/pegawai/_pegawai'
    | '/dashboard/pengadu'
    | '/dashboard/pengadu/_pengadu'
    | '/dashboard/responden'
    | '/dashboard/responden/_responden'
    | '/dashboard/pegawai/_pegawai/senarai-aduan'
    | '/dashboard/pengadu/_pengadu/senarai-aduan'
    | '/dashboard/responden/_responden/senarai-aduan'
    | '/dashboard/admin/_admin/'
    | '/dashboard/pegawai/_pegawai/'
    | '/dashboard/pengadu/_pengadu/'
    | '/dashboard/responden/_responden/'
    | '/dashboard/admin/_admin/manage/external-users'
    | '/dashboard/admin/_admin/manage/internal-users'
    | '/dashboard/pegawai/_pegawai/aduan-baru/borang-3'
    | '/dashboard/pegawai/_pegawai/aduan-baru/borang-4'
    | '/dashboard/pengadu/_pengadu/aduan-baru/borang-1'
    | '/dashboard/responden/_responden/aduan-baru/borang-2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginRoute: typeof LoginRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardPegawaiRoute: typeof DashboardPegawaiRouteWithChildren
  DashboardPengaduRoute: typeof DashboardPengaduRouteWithChildren
  DashboardRespondenRoute: typeof DashboardRespondenRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginRoute: LoginRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardPegawaiRoute: DashboardPegawaiRouteWithChildren,
  DashboardPengaduRoute: DashboardPengaduRouteWithChildren,
  DashboardRespondenRoute: DashboardRespondenRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/dashboard/admin",
        "/dashboard/pegawai",
        "/dashboard/pengadu",
        "/dashboard/responden"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/dashboard/admin": {
      "filePath": "dashboard/admin",
      "children": [
        "/dashboard/admin/_admin"
      ]
    },
    "/dashboard/admin/_admin": {
      "filePath": "dashboard/admin/_admin.tsx",
      "parent": "/dashboard/admin",
      "children": [
        "/dashboard/admin/_admin/",
        "/dashboard/admin/_admin/manage/external-users",
        "/dashboard/admin/_admin/manage/internal-users"
      ]
    },
    "/dashboard/pegawai": {
      "filePath": "dashboard/pegawai",
      "children": [
        "/dashboard/pegawai/_pegawai"
      ]
    },
    "/dashboard/pegawai/_pegawai": {
      "filePath": "dashboard/pegawai/_pegawai.tsx",
      "parent": "/dashboard/pegawai",
      "children": [
        "/dashboard/pegawai/_pegawai/senarai-aduan",
        "/dashboard/pegawai/_pegawai/",
        "/dashboard/pegawai/_pegawai/aduan-baru/borang-3",
        "/dashboard/pegawai/_pegawai/aduan-baru/borang-4"
      ]
    },
    "/dashboard/pengadu": {
      "filePath": "dashboard/pengadu",
      "children": [
        "/dashboard/pengadu/_pengadu"
      ]
    },
    "/dashboard/pengadu/_pengadu": {
      "filePath": "dashboard/pengadu/_pengadu.tsx",
      "parent": "/dashboard/pengadu",
      "children": [
        "/dashboard/pengadu/_pengadu/senarai-aduan",
        "/dashboard/pengadu/_pengadu/",
        "/dashboard/pengadu/_pengadu/aduan-baru/borang-1"
      ]
    },
    "/dashboard/responden": {
      "filePath": "dashboard/responden",
      "children": [
        "/dashboard/responden/_responden"
      ]
    },
    "/dashboard/responden/_responden": {
      "filePath": "dashboard/responden/_responden.tsx",
      "parent": "/dashboard/responden",
      "children": [
        "/dashboard/responden/_responden/senarai-aduan",
        "/dashboard/responden/_responden/",
        "/dashboard/responden/_responden/aduan-baru/borang-2"
      ]
    },
    "/dashboard/pegawai/_pegawai/senarai-aduan": {
      "filePath": "dashboard/pegawai/_pegawai/senarai-aduan.tsx",
      "parent": "/dashboard/pegawai/_pegawai"
    },
    "/dashboard/pengadu/_pengadu/senarai-aduan": {
      "filePath": "dashboard/pengadu/_pengadu/senarai-aduan.tsx",
      "parent": "/dashboard/pengadu/_pengadu"
    },
    "/dashboard/responden/_responden/senarai-aduan": {
      "filePath": "dashboard/responden/_responden/senarai-aduan.tsx",
      "parent": "/dashboard/responden/_responden"
    },
    "/dashboard/admin/_admin/": {
      "filePath": "dashboard/admin/_admin.index.tsx",
      "parent": "/dashboard/admin/_admin"
    },
    "/dashboard/pegawai/_pegawai/": {
      "filePath": "dashboard/pegawai/_pegawai.index.tsx",
      "parent": "/dashboard/pegawai/_pegawai"
    },
    "/dashboard/pengadu/_pengadu/": {
      "filePath": "dashboard/pengadu/_pengadu.index.tsx",
      "parent": "/dashboard/pengadu/_pengadu"
    },
    "/dashboard/responden/_responden/": {
      "filePath": "dashboard/responden/_responden.index.tsx",
      "parent": "/dashboard/responden/_responden"
    },
    "/dashboard/admin/_admin/manage/external-users": {
      "filePath": "dashboard/admin/_admin/manage/external-users.tsx",
      "parent": "/dashboard/admin/_admin"
    },
    "/dashboard/admin/_admin/manage/internal-users": {
      "filePath": "dashboard/admin/_admin/manage/internal-users.tsx",
      "parent": "/dashboard/admin/_admin"
    },
    "/dashboard/pegawai/_pegawai/aduan-baru/borang-3": {
      "filePath": "dashboard/pegawai/_pegawai/aduan-baru/borang-3.tsx",
      "parent": "/dashboard/pegawai/_pegawai"
    },
    "/dashboard/pegawai/_pegawai/aduan-baru/borang-4": {
      "filePath": "dashboard/pegawai/_pegawai/aduan-baru/borang-4.tsx",
      "parent": "/dashboard/pegawai/_pegawai"
    },
    "/dashboard/pengadu/_pengadu/aduan-baru/borang-1": {
      "filePath": "dashboard/pengadu/_pengadu/aduan-baru/borang-1.tsx",
      "parent": "/dashboard/pengadu/_pengadu"
    },
    "/dashboard/responden/_responden/aduan-baru/borang-2": {
      "filePath": "dashboard/responden/_responden/aduan-baru/borang-2.tsx",
      "parent": "/dashboard/responden/_responden"
    }
  }
}
ROUTE_MANIFEST_END */
